name: marketplace

on:
  push:
    branches:
      - "main"

jobs:
  build:
    - name: Build
      runs-on: ubuntu:latest
      steps:
        - uses: actions/checkout@v2
        - uses: cclauss/Find-Python-syntax-errors-action@master
      
