name: Third

env:
  WORKSPACE_ENV_VARIABLE: "Workspace level custom environment variable."

on:
  push:
    branches:
      - "main"

jobs:
  job1:
    env:
      JOB_ENV_VARIABLE: "Job level custom environment variable."
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        env:
          STEP_ENV_VARIABLE: "Step level custom environment variable."
        run: |
          echo "Accessing environment variables in run command"
          echo "$WORKSPACE_ENV_VARIABLE"
          echo "$JOB_ENV_VARIABLE"
          echo "$STEP_ENV_VARIABLE"
          echo "----------------------------------------------"
          echo "Accessing environment variables using env context"
          echo "${{ env.WORKSPACE_ENV_VARIABLE }}"
          echo "${{ env.JOB_ENV_VARIABLE }}"
          echo "${{ env.STEP_ENV_VARIABLE }} not defined"
  job2:
    name: Second Job
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        run: date
  job3:
    name: Third Job
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        run: date
  job4:
    name: Fourth Job
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: Step One
        run: date
